### ISSUE TITLE
Dark theme support

### ISSUE THREAD

**Issue by Keith94** [ExE-Boss/reload-in-urlbar#1]
The reload button is too dark when selecting a dark theme in Nightly. Maybe the icon can be user customizable for light and dark themes.

**Comment by Keith94** [comment]
Any news?

**Comment by ExE-Boss** [comment]
Right now, the way to enable this is to go to `about:config` and set `svg.context‑properties.content.enabled` to `true`, as the icons support [`‑moz‑context‑properties`](https://developer.mozilla.org/docs/Web/CSS/-moz-context-properties) ([I also put this information on the AMO listing page](https://addons.mozilla.org/firefox/addon/reload-in-urlbar/)).

**Comment by Keith94** [comment]
Oh thanks - that worked. :)
